/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoresIdRouteImport } from './routes/stores_.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as MerchantTablesRouteImport } from './routes/merchant.tables'
import { Route as MerchantStoreRouteImport } from './routes/merchant.store'
import { Route as MerchantRetailRouteImport } from './routes/merchant.retail'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantMenuRouteImport } from './routes/merchant.menu'
import { Route as MerchantLoyaltyRouteImport } from './routes/merchant.loyalty'
import { Route as MerchantAnalyticsRouteImport } from './routes/merchant.analytics'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerOrderRouteImport } from './routes/customer.order'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthMerchantRouteImport } from './routes/auth/merchant'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as MMerchantSlugTableTableTokenRouteImport } from './routes/m/$merchantSlug/table/$tableToken'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores_/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantTablesRoute = MerchantTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantStoreRoute = MerchantStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantRetailRoute = MerchantRetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoyaltyRoute = MerchantLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAnalyticsRoute = MerchantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MerchantRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderRoute = CustomerOrderRouteImport.update({
  id: '/customer/order',
  path: '/customer/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMerchantRoute = AuthMerchantRouteImport.update({
  id: '/auth/merchant',
  path: '/auth/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const MMerchantSlugTableTableTokenRoute =
  MMerchantSlugTableTableTokenRouteImport.update({
    id: '/m/$merchantSlug/table/$tableToken',
    path: '/m/$merchantSlug/table/$tableToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/retail': typeof RetailRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/retail': typeof MerchantRetailRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/m/$merchantSlug/table/$tableToken': typeof MMerchantSlugTableTableTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/retail': typeof RetailRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/retail': typeof MerchantRetailRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/m/$merchantSlug/table/$tableToken': typeof MMerchantSlugTableTableTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/retail': typeof RetailRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/retail': typeof MerchantRetailRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/stores_/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/m/$merchantSlug/table/$tableToken': typeof MMerchantSlugTableTableTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/merchant'
    | '/missions'
    | '/profile'
    | '/retail'
    | '/rewards'
    | '/stores'
    | '/admin/analytics'
    | '/admin/merchants'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/customer/order'
    | '/customer/orders'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/retail'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/stores/$id'
    | '/admin/'
    | '/auth/'
    | '/merchant/'
    | '/m/$merchantSlug/table/$tableToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/missions'
    | '/profile'
    | '/retail'
    | '/rewards'
    | '/stores'
    | '/admin/analytics'
    | '/admin/merchants'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/customer/order'
    | '/customer/orders'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/retail'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/stores/$id'
    | '/admin'
    | '/auth'
    | '/merchant'
    | '/m/$merchantSlug/table/$tableToken'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/merchant'
    | '/missions'
    | '/profile'
    | '/retail'
    | '/rewards'
    | '/stores'
    | '/admin/analytics'
    | '/admin/merchants'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/customer/order'
    | '/customer/orders'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/retail'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/stores_/$id'
    | '/admin/'
    | '/auth/'
    | '/merchant/'
    | '/m/$merchantSlug/table/$tableToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  RetailRoute: typeof RetailRoute
  RewardsRoute: typeof RewardsRoute
  StoresRoute: typeof StoresRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMerchantRoute: typeof AuthMerchantRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CustomerOrderRoute: typeof CustomerOrderRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  OrdersIdRoute: typeof OrdersIdRoute
  StoresIdRoute: typeof StoresIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  MMerchantSlugTableTableTokenRoute: typeof MMerchantSlugTableTableTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stores_/$id': {
      id: '/stores_/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/tables': {
      id: '/merchant/tables'
      path: '/tables'
      fullPath: '/merchant/tables'
      preLoaderRoute: typeof MerchantTablesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/store': {
      id: '/merchant/store'
      path: '/store'
      fullPath: '/merchant/store'
      preLoaderRoute: typeof MerchantStoreRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/retail': {
      id: '/merchant/retail'
      path: '/retail'
      fullPath: '/merchant/retail'
      preLoaderRoute: typeof MerchantRetailRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/loyalty': {
      id: '/merchant/loyalty'
      path: '/loyalty'
      fullPath: '/merchant/loyalty'
      preLoaderRoute: typeof MerchantLoyaltyRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/analytics': {
      id: '/merchant/analytics'
      path: '/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof MerchantAnalyticsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/order': {
      id: '/customer/order'
      path: '/customer/order'
      fullPath: '/customer/order'
      preLoaderRoute: typeof CustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/merchant': {
      id: '/auth/merchant'
      path: '/auth/merchant'
      fullPath: '/auth/merchant'
      preLoaderRoute: typeof AuthMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/m/$merchantSlug/table/$tableToken': {
      id: '/m/$merchantSlug/table/$tableToken'
      path: '/m/$merchantSlug/table/$tableToken'
      fullPath: '/m/$merchantSlug/table/$tableToken'
      preLoaderRoute: typeof MMerchantSlugTableTableTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantAnalyticsRoute: typeof MerchantAnalyticsRoute
  MerchantLoyaltyRoute: typeof MerchantLoyaltyRoute
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantRetailRoute: typeof MerchantRetailRoute
  MerchantStoreRoute: typeof MerchantStoreRoute
  MerchantTablesRoute: typeof MerchantTablesRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAnalyticsRoute: MerchantAnalyticsRoute,
  MerchantLoyaltyRoute: MerchantLoyaltyRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantRetailRoute: MerchantRetailRoute,
  MerchantStoreRoute: MerchantStoreRoute,
  MerchantTablesRoute: MerchantTablesRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoyaltyRoute: LoyaltyRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  RetailRoute: RetailRoute,
  RewardsRoute: RewardsRoute,
  StoresRoute: StoresRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMerchantRoute: AuthMerchantRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CustomerOrderRoute: CustomerOrderRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  OrdersIdRoute: OrdersIdRoute,
  StoresIdRoute: StoresIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  MMerchantSlugTableTableTokenRoute: MMerchantSlugTableTableTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
