/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PosRouteImport } from './routes/pos'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoresIdRouteImport } from './routes/stores_.$id'
import { Route as PosShiftRouteImport } from './routes/pos.shift'
import { Route as PosCreditRouteImport } from './routes/pos.credit'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as MerchantTablesRouteImport } from './routes/merchant.tables'
import { Route as MerchantStoreRouteImport } from './routes/merchant.store'
import { Route as MerchantShiftsRouteImport } from './routes/merchant.shifts'
import { Route as MerchantShiftWorkersRouteImport } from './routes/merchant.shift-workers'
import { Route as MerchantRetailRouteImport } from './routes/merchant.retail'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantMenuRouteImport } from './routes/merchant.menu'
import { Route as MerchantMembersRouteImport } from './routes/merchant.members'
import { Route as MerchantLoyaltyRouteImport } from './routes/merchant.loyalty'
import { Route as MerchantFiscalReportRouteImport } from './routes/merchant.fiscal-report'
import { Route as MerchantDailyReportRouteImport } from './routes/merchant.daily-report'
import { Route as MerchantCreditRouteImport } from './routes/merchant.credit'
import { Route as MerchantAnalyticsRouteImport } from './routes/merchant.analytics'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerOrderRouteImport } from './routes/customer.order'
import { Route as AuthShiftRouteImport } from './routes/auth.shift'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthMerchantRouteImport } from './routes/auth/merchant'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthAdminRouteImport } from './routes/auth/admin'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PosPaymentOrderIdRouteImport } from './routes/pos.payment.$orderId'
import { Route as PosOrdersNewRouteImport } from './routes/pos.orders.new'
import { Route as PosBillOrderIdRouteImport } from './routes/pos.bill.$orderId'
import { Route as MerchantShiftReportShiftIdRouteImport } from './routes/merchant.shift-report.$shiftId'
import { Route as PosPaymentOrderIdReceiptRouteImport } from './routes/pos.payment.$orderId.receipt'
import { Route as MMerchantSlugTableTableTokenRouteImport } from './routes/m/$merchantSlug/table/$tableToken'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores_/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PosShiftRoute = PosShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => PosRoute,
} as any)
const PosCreditRoute = PosCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => PosRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantTablesRoute = MerchantTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantStoreRoute = MerchantStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantShiftsRoute = MerchantShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantShiftWorkersRoute = MerchantShiftWorkersRouteImport.update({
  id: '/shift-workers',
  path: '/shift-workers',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantRetailRoute = MerchantRetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMembersRoute = MerchantMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoyaltyRoute = MerchantLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantFiscalReportRoute = MerchantFiscalReportRouteImport.update({
  id: '/fiscal-report',
  path: '/fiscal-report',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantDailyReportRoute = MerchantDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCreditRoute = MerchantCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAnalyticsRoute = MerchantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MerchantRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderRoute = CustomerOrderRouteImport.update({
  id: '/customer/order',
  path: '/customer/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShiftRoute = AuthShiftRouteImport.update({
  id: '/auth/shift',
  path: '/auth/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMerchantRoute = AuthMerchantRouteImport.update({
  id: '/auth/merchant',
  path: '/auth/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PosPaymentOrderIdRoute = PosPaymentOrderIdRouteImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => PosRoute,
} as any)
const PosOrdersNewRoute = PosOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => PosRoute,
} as any)
const PosBillOrderIdRoute = PosBillOrderIdRouteImport.update({
  id: '/bill/$orderId',
  path: '/bill/$orderId',
  getParentRoute: () => PosRoute,
} as any)
const MerchantShiftReportShiftIdRoute =
  MerchantShiftReportShiftIdRouteImport.update({
    id: '/shift-report/$shiftId',
    path: '/shift-report/$shiftId',
    getParentRoute: () => MerchantRoute,
  } as any)
const PosPaymentOrderIdReceiptRoute =
  PosPaymentOrderIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => PosPaymentOrderIdRoute,
  } as any)
const MMerchantSlugTableTableTokenRoute =
  MMerchantSlugTableTableTokenRouteImport.update({
    id: '/m/$merchantSlug/table/$tableToken',
    path: '/m/$merchantSlug/table/$tableToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/retail': typeof RetailRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/shift': typeof AuthShiftRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/daily-report': typeof MerchantDailyReportRoute
  '/merchant/fiscal-report': typeof MerchantFiscalReportRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/members': typeof MerchantMembersRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/retail': typeof MerchantRetailRoute
  '/merchant/shift-workers': typeof MerchantShiftWorkersRoute
  '/merchant/shifts': typeof MerchantShiftsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pos/credit': typeof PosCreditRoute
  '/pos/shift': typeof PosShiftRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/pos/': typeof PosIndexRoute
  '/merchant/shift-report/$shiftId': typeof MerchantShiftReportShiftIdRoute
  '/pos/bill/$orderId': typeof PosBillOrderIdRoute
  '/pos/orders/new': typeof PosOrdersNewRoute
  '/pos/payment/$orderId': typeof PosPaymentOrderIdRouteWithChildren
  '/m/$merchantSlug/table/$tableToken': typeof MMerchantSlugTableTableTokenRoute
  '/pos/payment/$orderId/receipt': typeof PosPaymentOrderIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/retail': typeof RetailRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/shift': typeof AuthShiftRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/daily-report': typeof MerchantDailyReportRoute
  '/merchant/fiscal-report': typeof MerchantFiscalReportRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/members': typeof MerchantMembersRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/retail': typeof MerchantRetailRoute
  '/merchant/shift-workers': typeof MerchantShiftWorkersRoute
  '/merchant/shifts': typeof MerchantShiftsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pos/credit': typeof PosCreditRoute
  '/pos/shift': typeof PosShiftRoute
  '/stores/$id': typeof StoresIdRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/pos': typeof PosIndexRoute
  '/merchant/shift-report/$shiftId': typeof MerchantShiftReportShiftIdRoute
  '/pos/bill/$orderId': typeof PosBillOrderIdRoute
  '/pos/orders/new': typeof PosOrdersNewRoute
  '/pos/payment/$orderId': typeof PosPaymentOrderIdRouteWithChildren
  '/m/$merchantSlug/table/$tableToken': typeof MMerchantSlugTableTableTokenRoute
  '/pos/payment/$orderId/receipt': typeof PosPaymentOrderIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/retail': typeof RetailRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/shift': typeof AuthShiftRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/daily-report': typeof MerchantDailyReportRoute
  '/merchant/fiscal-report': typeof MerchantFiscalReportRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/members': typeof MerchantMembersRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/retail': typeof MerchantRetailRoute
  '/merchant/shift-workers': typeof MerchantShiftWorkersRoute
  '/merchant/shifts': typeof MerchantShiftsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pos/credit': typeof PosCreditRoute
  '/pos/shift': typeof PosShiftRoute
  '/stores_/$id': typeof StoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/pos/': typeof PosIndexRoute
  '/merchant/shift-report/$shiftId': typeof MerchantShiftReportShiftIdRoute
  '/pos/bill/$orderId': typeof PosBillOrderIdRoute
  '/pos/orders/new': typeof PosOrdersNewRoute
  '/pos/payment/$orderId': typeof PosPaymentOrderIdRouteWithChildren
  '/m/$merchantSlug/table/$tableToken': typeof MMerchantSlugTableTableTokenRoute
  '/pos/payment/$orderId/receipt': typeof PosPaymentOrderIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/merchant'
    | '/missions'
    | '/pos'
    | '/profile'
    | '/retail'
    | '/rewards'
    | '/stores'
    | '/admin/analytics'
    | '/admin/merchants'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/auth/shift'
    | '/customer/order'
    | '/customer/orders'
    | '/merchant/analytics'
    | '/merchant/credit'
    | '/merchant/daily-report'
    | '/merchant/fiscal-report'
    | '/merchant/loyalty'
    | '/merchant/members'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/retail'
    | '/merchant/shift-workers'
    | '/merchant/shifts'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/pos/credit'
    | '/pos/shift'
    | '/stores/$id'
    | '/admin/'
    | '/auth/'
    | '/merchant/'
    | '/pos/'
    | '/merchant/shift-report/$shiftId'
    | '/pos/bill/$orderId'
    | '/pos/orders/new'
    | '/pos/payment/$orderId'
    | '/m/$merchantSlug/table/$tableToken'
    | '/pos/payment/$orderId/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/missions'
    | '/profile'
    | '/retail'
    | '/rewards'
    | '/stores'
    | '/admin/analytics'
    | '/admin/merchants'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/auth/shift'
    | '/customer/order'
    | '/customer/orders'
    | '/merchant/analytics'
    | '/merchant/credit'
    | '/merchant/daily-report'
    | '/merchant/fiscal-report'
    | '/merchant/loyalty'
    | '/merchant/members'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/retail'
    | '/merchant/shift-workers'
    | '/merchant/shifts'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/pos/credit'
    | '/pos/shift'
    | '/stores/$id'
    | '/admin'
    | '/auth'
    | '/merchant'
    | '/pos'
    | '/merchant/shift-report/$shiftId'
    | '/pos/bill/$orderId'
    | '/pos/orders/new'
    | '/pos/payment/$orderId'
    | '/m/$merchantSlug/table/$tableToken'
    | '/pos/payment/$orderId/receipt'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/merchant'
    | '/missions'
    | '/pos'
    | '/profile'
    | '/retail'
    | '/rewards'
    | '/stores'
    | '/admin/analytics'
    | '/admin/merchants'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/auth/shift'
    | '/customer/order'
    | '/customer/orders'
    | '/merchant/analytics'
    | '/merchant/credit'
    | '/merchant/daily-report'
    | '/merchant/fiscal-report'
    | '/merchant/loyalty'
    | '/merchant/members'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/retail'
    | '/merchant/shift-workers'
    | '/merchant/shifts'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/pos/credit'
    | '/pos/shift'
    | '/stores_/$id'
    | '/admin/'
    | '/auth/'
    | '/merchant/'
    | '/pos/'
    | '/merchant/shift-report/$shiftId'
    | '/pos/bill/$orderId'
    | '/pos/orders/new'
    | '/pos/payment/$orderId'
    | '/m/$merchantSlug/table/$tableToken'
    | '/pos/payment/$orderId/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  PosRoute: typeof PosRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RetailRoute: typeof RetailRoute
  RewardsRoute: typeof RewardsRoute
  StoresRoute: typeof StoresRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMerchantRoute: typeof AuthMerchantRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthShiftRoute: typeof AuthShiftRoute
  CustomerOrderRoute: typeof CustomerOrderRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  OrdersIdRoute: typeof OrdersIdRoute
  StoresIdRoute: typeof StoresIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  MMerchantSlugTableTableTokenRoute: typeof MMerchantSlugTableTableTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stores_/$id': {
      id: '/stores_/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/shift': {
      id: '/pos/shift'
      path: '/shift'
      fullPath: '/pos/shift'
      preLoaderRoute: typeof PosShiftRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/credit': {
      id: '/pos/credit'
      path: '/credit'
      fullPath: '/pos/credit'
      preLoaderRoute: typeof PosCreditRouteImport
      parentRoute: typeof PosRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/tables': {
      id: '/merchant/tables'
      path: '/tables'
      fullPath: '/merchant/tables'
      preLoaderRoute: typeof MerchantTablesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/store': {
      id: '/merchant/store'
      path: '/store'
      fullPath: '/merchant/store'
      preLoaderRoute: typeof MerchantStoreRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/shifts': {
      id: '/merchant/shifts'
      path: '/shifts'
      fullPath: '/merchant/shifts'
      preLoaderRoute: typeof MerchantShiftsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/shift-workers': {
      id: '/merchant/shift-workers'
      path: '/shift-workers'
      fullPath: '/merchant/shift-workers'
      preLoaderRoute: typeof MerchantShiftWorkersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/retail': {
      id: '/merchant/retail'
      path: '/retail'
      fullPath: '/merchant/retail'
      preLoaderRoute: typeof MerchantRetailRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/members': {
      id: '/merchant/members'
      path: '/members'
      fullPath: '/merchant/members'
      preLoaderRoute: typeof MerchantMembersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/loyalty': {
      id: '/merchant/loyalty'
      path: '/loyalty'
      fullPath: '/merchant/loyalty'
      preLoaderRoute: typeof MerchantLoyaltyRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/fiscal-report': {
      id: '/merchant/fiscal-report'
      path: '/fiscal-report'
      fullPath: '/merchant/fiscal-report'
      preLoaderRoute: typeof MerchantFiscalReportRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/daily-report': {
      id: '/merchant/daily-report'
      path: '/daily-report'
      fullPath: '/merchant/daily-report'
      preLoaderRoute: typeof MerchantDailyReportRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/credit': {
      id: '/merchant/credit'
      path: '/credit'
      fullPath: '/merchant/credit'
      preLoaderRoute: typeof MerchantCreditRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/analytics': {
      id: '/merchant/analytics'
      path: '/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof MerchantAnalyticsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/order': {
      id: '/customer/order'
      path: '/customer/order'
      fullPath: '/customer/order'
      preLoaderRoute: typeof CustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/shift': {
      id: '/auth/shift'
      path: '/auth/shift'
      fullPath: '/auth/shift'
      preLoaderRoute: typeof AuthShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/merchant': {
      id: '/auth/merchant'
      path: '/auth/merchant'
      fullPath: '/auth/merchant'
      preLoaderRoute: typeof AuthMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pos/payment/$orderId': {
      id: '/pos/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/pos/payment/$orderId'
      preLoaderRoute: typeof PosPaymentOrderIdRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/orders/new': {
      id: '/pos/orders/new'
      path: '/orders/new'
      fullPath: '/pos/orders/new'
      preLoaderRoute: typeof PosOrdersNewRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/bill/$orderId': {
      id: '/pos/bill/$orderId'
      path: '/bill/$orderId'
      fullPath: '/pos/bill/$orderId'
      preLoaderRoute: typeof PosBillOrderIdRouteImport
      parentRoute: typeof PosRoute
    }
    '/merchant/shift-report/$shiftId': {
      id: '/merchant/shift-report/$shiftId'
      path: '/shift-report/$shiftId'
      fullPath: '/merchant/shift-report/$shiftId'
      preLoaderRoute: typeof MerchantShiftReportShiftIdRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/pos/payment/$orderId/receipt': {
      id: '/pos/payment/$orderId/receipt'
      path: '/receipt'
      fullPath: '/pos/payment/$orderId/receipt'
      preLoaderRoute: typeof PosPaymentOrderIdReceiptRouteImport
      parentRoute: typeof PosPaymentOrderIdRoute
    }
    '/m/$merchantSlug/table/$tableToken': {
      id: '/m/$merchantSlug/table/$tableToken'
      path: '/m/$merchantSlug/table/$tableToken'
      fullPath: '/m/$merchantSlug/table/$tableToken'
      preLoaderRoute: typeof MMerchantSlugTableTableTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantAnalyticsRoute: typeof MerchantAnalyticsRoute
  MerchantCreditRoute: typeof MerchantCreditRoute
  MerchantDailyReportRoute: typeof MerchantDailyReportRoute
  MerchantFiscalReportRoute: typeof MerchantFiscalReportRoute
  MerchantLoyaltyRoute: typeof MerchantLoyaltyRoute
  MerchantMembersRoute: typeof MerchantMembersRoute
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantRetailRoute: typeof MerchantRetailRoute
  MerchantShiftWorkersRoute: typeof MerchantShiftWorkersRoute
  MerchantShiftsRoute: typeof MerchantShiftsRoute
  MerchantStoreRoute: typeof MerchantStoreRoute
  MerchantTablesRoute: typeof MerchantTablesRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantShiftReportShiftIdRoute: typeof MerchantShiftReportShiftIdRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAnalyticsRoute: MerchantAnalyticsRoute,
  MerchantCreditRoute: MerchantCreditRoute,
  MerchantDailyReportRoute: MerchantDailyReportRoute,
  MerchantFiscalReportRoute: MerchantFiscalReportRoute,
  MerchantLoyaltyRoute: MerchantLoyaltyRoute,
  MerchantMembersRoute: MerchantMembersRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantRetailRoute: MerchantRetailRoute,
  MerchantShiftWorkersRoute: MerchantShiftWorkersRoute,
  MerchantShiftsRoute: MerchantShiftsRoute,
  MerchantStoreRoute: MerchantStoreRoute,
  MerchantTablesRoute: MerchantTablesRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantShiftReportShiftIdRoute: MerchantShiftReportShiftIdRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface PosPaymentOrderIdRouteChildren {
  PosPaymentOrderIdReceiptRoute: typeof PosPaymentOrderIdReceiptRoute
}

const PosPaymentOrderIdRouteChildren: PosPaymentOrderIdRouteChildren = {
  PosPaymentOrderIdReceiptRoute: PosPaymentOrderIdReceiptRoute,
}

const PosPaymentOrderIdRouteWithChildren =
  PosPaymentOrderIdRoute._addFileChildren(PosPaymentOrderIdRouteChildren)

interface PosRouteChildren {
  PosCreditRoute: typeof PosCreditRoute
  PosShiftRoute: typeof PosShiftRoute
  PosIndexRoute: typeof PosIndexRoute
  PosBillOrderIdRoute: typeof PosBillOrderIdRoute
  PosOrdersNewRoute: typeof PosOrdersNewRoute
  PosPaymentOrderIdRoute: typeof PosPaymentOrderIdRouteWithChildren
}

const PosRouteChildren: PosRouteChildren = {
  PosCreditRoute: PosCreditRoute,
  PosShiftRoute: PosShiftRoute,
  PosIndexRoute: PosIndexRoute,
  PosBillOrderIdRoute: PosBillOrderIdRoute,
  PosOrdersNewRoute: PosOrdersNewRoute,
  PosPaymentOrderIdRoute: PosPaymentOrderIdRouteWithChildren,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoyaltyRoute: LoyaltyRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MissionsRoute: MissionsRoute,
  PosRoute: PosRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RetailRoute: RetailRoute,
  RewardsRoute: RewardsRoute,
  StoresRoute: StoresRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMerchantRoute: AuthMerchantRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthShiftRoute: AuthShiftRoute,
  CustomerOrderRoute: CustomerOrderRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  OrdersIdRoute: OrdersIdRoute,
  StoresIdRoute: StoresIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  MMerchantSlugTableTableTokenRoute: MMerchantSlugTableTableTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
